sudo: false

cache:
  directories:
  - $HOME/.gradle

language: groovy

jdk:
- oraclejdk8

env:
- TERM=dumb

before_script:
  - ./gradlew --version

script:
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)